language: python
python:
  - "3.6"
  - "3.7"
install: pip install -r requirements-dev.txt
script:
  - ci/unittest.sh
  - ci/quality.sh
jobs:
  include:
    - stage: deploy
      if: tag IS present
      python: 3.7
      script: python setup.py sdist bdist_wheel
      deploy:
        - provider: pypi
          skip_cleanup: true
          on:
            tags: true
          user: fniessink
          password:
            secure: FI9Q2kC5D6i2hjK7t0GTVzYIgmU7H9GoI0qqtzVtT6V7gfV74HtfPxuIbkF6HND09GY1moSF5I0vyR8Bm2nMxEs+9PflYtNUMeNlyrEEof/brbYIrKujPGr6wVdgT4iZlMAVeybRTWhPQpo5PFsGuGcQa5cZOzt4fPPy/KO8C0c=
